Update docker/setup-buildx-action@v3

diff --git a/tests/test-append.yml b/tests/test-append.yml
--- a/tests/test-append.yml
+++ b/tests/test-append.yml
@@ -10,34 +10,34 @@ jobs:
         id: builder
         uses: .
         with:
-          driver: 'docker-container'
+          driver: docker-container
           use: 'true'
-      - name: Append node to builder
-        id: action
+      - name: Assert initial builder created
+        env:
+          NAME: ${{ steps.builder.outputs.name }}
+        run: |
+          echo "name: $NAME"
+          if [ -z "$NAME" ]; then
+            echo "FAIL: expected builder name to be set"
+            exit 1
+          fi
+          echo "PASS: initial builder created: $NAME"
+      - id: action
         uses: .
         with:
-          driver: 'docker-container'
           name: ${{ steps.builder.outputs.name }}
           append: |
             - endpoint: unix:///var/run/docker.sock
           use: 'true'
-      - name: Assert builder name output is set
+      - name: Assert builder name output is set after append
         env:
-          ACTUAL: ${{ steps.action.outputs.name }}
+          NAME: ${{ steps.action.outputs.name }}
+          NODES: ${{ steps.action.outputs.nodes }}
         run: |
-          echo "actual: $ACTUAL"
-          if [ -z "$ACTUAL" ]; then
+          echo "name: $NAME"
+          echo "nodes: $NODES"
+          if [ -z "$NAME" ]; then
             echo "FAIL: expected builder name to be set"
-            exit 1
-          fi
-          echo "PASS"
-      - name: Assert nodes output is set
-        env:
-          ACTUAL: ${{ steps.action.outputs.nodes }}
-        run: |
-          echo "actual: $ACTUAL"
-          if [ -z "$ACTUAL" ]; then
-            echo "FAIL: expected nodes to be set"
             exit 1
           fi
           echo "PASS"
